# Dense Layers

## shapes of dense layers

In [8]:
import tensorflow as tf
from tensorflow.keras.layers import Dense 

N, n_feature = 8, 10 
X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3 
dense = Dense(units = n_neuron, activation = 'sigmoid')
Y = dense(X) # (8, 3)  (N, n_neuron)

W, B = dense.get_weights() # W -> (10,3), B -> (3, ) weight와 bias는 바뀌지 않음. 

print('====== Input / Weights / Bias ======')
print("X: ", X.shape) # (N, n_feature)
print("W: ", W.shape) # (n_feature, n_neuron)
print("B: ", B.shape) # (n_neuron, )
print("Y: ", Y.shape) # (N, n_neuron)



====== Input / Weights / Bias ======
X:  (8, 10)
W:  (10, 3)
B:  (3,)
Y:  (8, 3)


In [9]:
## output calculations

In [18]:
import numpy as np
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul
from tensorflow.keras.layers import Dense 

N, n_feature = 4, 10 
X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3 
dense = Dense(units = n_neuron, activation = 'sigmoid')
Y_tf = dense(X) 

W, B = dense.get_weights() 
print("Y(Tensorflow) :\n", Y_tf.numpy())

# calculations with matrix multiplication (직접 구현)
z = matmul(X, W) + B
Y_man_matmul = 1/(1+exp(-z))
print("Y(with matrix multiplication) :\n", Y_man_matmul.numpy())

# calculate with dot products
Y_man_vec = np.zeros(shape=(N, n_neuron)) # output matrix 
for x_idx in range(N):
  x = X[x_idx]

  for nu_idx in range(n_neuron):
    w, b = W[:, nu_idx], B[nu_idx]

    z = tf.reduce_sum(x * w) + b
    a = 1/(1+np.exp(-z))
    Y_man_vec[x_idx, nu_idx] = a

print("Y(with dot products):\n", Y_man_vec)

Y(Tensorflow) :
 [[0.4635984  0.44072    0.77959824]
 [0.76098895 0.5815208  0.34852397]
 [0.8679917  0.47808725 0.27944428]
 [0.1936361  0.31111518 0.97340554]]
Y(with matrix multiplication) :
 [[0.4635984  0.44072    0.77959824]
 [0.7609889  0.58152074 0.34852397]
 [0.86799175 0.47808725 0.27944428]
 [0.1936361  0.31111518 0.9734055 ]]
Y(with dot products):
 [[0.46359842 0.44072    0.77959825]
 [0.7609889  0.58152074 0.34852399]
 [0.86799172 0.47808726 0.27944427]
 [0.19363616 0.31111518 0.97340554]]


# cascaded dense layers

## shapes of cascaded dense layers

In [29]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neurons = [3, 5]
dense1 = Dense(units=n_neurons[0], activation='sigmoid')
dense2 = Dense(units=n_neurons[1], activation='sigmoid')

# forward propagation
A1 = dense1(X)
Y = dense2(A1)

# get weight/bias
W1, B1 = dense1.get_weights()
W2, B2 = dense2.get_weights()

print("X: {}\n".format(X.shape))

print("W1: ", W1.shape)
print("B1: ", B1.shape)
print("A1: {}\n".format(A1.shape))

print("W2: ", W2.shape)
print("B2: ", B2.shape)
print("Y: {}\n".format(Y.shape))

X: (4, 10)

W1:  (10, 3)
B1:  (3,)
A1: (4, 3)

W2:  (3, 5)
B2:  (5,)
Y: (4, 5)



## dense layers with python list

In [35]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neurons = [10,20,30,40,50,60,70,80,90,100]

dense_layers = list() # 10개의 object들이 만들어져 있음.
for n_neuron in n_neurons:
  dense = Dense(units=n_neuron, activation='relu')
  dense_layers.append(dense)

print("input : ", X.shape)
for dense_idx, dense in enumerate(dense_layers): # 반복문으로 모든 dense layer에 X값 통과시켜주기. 
  X = dense(X)
  print("After dense layer ", dense_idx)
  print(X.shape, '\n')
Y = X


input :  (4, 10)
After dense layer  0
(4, 10) 

After dense layer  1
(4, 20) 

After dense layer  2
(4, 30) 

After dense layer  3
(4, 40) 

After dense layer  4
(4, 50) 

After dense layer  5
(4, 60) 

After dense layer  6
(4, 70) 

After dense layer  7
(4, 80) 

After dense layer  8
(4, 90) 

After dense layer  9
(4, 100) 



## output calculations

In [44]:
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))
X_cp = tf.identity(X) # 다른 위치에 저장

n_neurons = [3, 4, 5]

dense_layers = list() 
for n_neuron in n_neurons:
  dense = Dense(units=n_neuron, activation='sigmoid')
  dense_layers.append(dense)

# forward propagation (Tensorflow)
W,B = list(), list()
for dense_idx, dense in enumerate(dense_layers): # 반복문으로 모든 dense layer에 X값 통과시켜주기. 
  X = dense(X)
  w,b = dense.get_weights()

  W.append(w)
  B.append(b)
print("Y(Tensorflow):\n", X.numpy())

# forward propagation (Manual)
for layer_idx in range(len(n_neurons)):
  w,b = W[layer_idx], B[layer_idx]

  X_cp = matmul(X_cp, w) + b
  X_cp = 1/(1+exp(-X_cp))
print("Y(Manual):\n", X_cp.numpy())

Y(Tensorflow):
 [[0.4315367  0.35073602 0.4935948  0.5365847  0.5642268 ]
 [0.45311648 0.39241004 0.4874445  0.53062105 0.53656495]
 [0.44664565 0.3836401  0.48522577 0.531838   0.54099905]
 [0.44851777 0.3722449  0.49577978 0.5301785  0.5532663 ]]
Y(Manual):
 [[0.43153673 0.35073602 0.4935948  0.5365847  0.5642268 ]
 [0.45311645 0.39241004 0.48744452 0.53062105 0.53656495]
 [0.44664565 0.3836401  0.48522574 0.53183806 0.5409991 ]
 [0.44851777 0.3722449  0.49577978 0.5301785  0.5532662 ]]
