In [ ]:
# activation function 만 만드는 방법과
# activation function 과 affine function을 같이 만드는 방법

# activation functions

## activation layers

In [10]:
import tensorflow as tf
from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation 

x = tf.random.normal(shape=(1,5)) # input setting

# imp. activation function
sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

# forward propagation (Tensorflow)
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

# forward progation (manual)
y_sigmoid_man = 1 / (1 + exp(-x))
y_tanh_man = (exp(x) - exp(-x)) / (exp(x) + exp(-x))
y_relu_man = maximum(x, 0)



print("x : {}\n{}\n".format(x.shape, x.numpy()))
print('Sigmoid(Tensorflow) : {}\n{}'.format(y_sigmoid_tf.shape, y_sigmoid_tf.numpy()))
print('Sigmoid(Manual) : {}\n{}\n'.format(y_sigmoid_man.shape, y_sigmoid_man.numpy()))

print('Tanh(Tensorflow) : {}\n{}'.format(y_tanh_tf.shape, y_tanh_tf.numpy()))
print('Tanh(Manual) : {}\n{}\n'.format(y_tanh_man.shape, y_tanh_man.numpy()))

print('Relu(Tensorflow) : {}\n{}'.format(y_relu_tf.shape, y_relu_tf.numpy()))
print('Relu(Manual) : {}\n{}\n'.format(y_relu_man.shape, y_relu_man.numpy()))



x : (1, 5)
[[-1.1584934   0.5299585  -0.18279271  3.0046482  -0.04527995]]

Sigmoid(Tensorflow) : (1, 5)
[[0.23894113 0.62947345 0.45442864 0.9527837  0.48868194]]
Sigmoid(Manual) : (1, 5)
[[0.23894115 0.6294734  0.45442867 0.9527837  0.4886819 ]]

Tanh(Tensorflow) : (1, 5)
[[-0.8205483   0.4853494  -0.18078364  0.9951005  -0.04524903]]
Tanh(Manual) : (1, 5)
[[-0.82054824  0.48534933 -0.18078361  0.9951003  -0.04524905]]

Relu(Tensorflow) : (1, 5)
[[0.        0.5299585 0.        3.0046482 0.       ]]
Relu(Manual) : (1, 5)
[[0.        0.5299585 0.        3.0046482 0.       ]]



## activation in dense layer

In [14]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.math import exp, maximum

x = tf.random.normal(shape=(1,5)) # input setting

# imp. artifical neurons 
dense_sigmoid = Dense(units=1, activation='sigmoid')
dense_tanh = Dense(units=1, activation='tanh')
dense_relu = Dense(units=1, activation='relu')

# forward propagation (Tensorflow)
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

print('AN with Sigmoid : {}\n{}'.format(y_sigmoid.shape, y_sigmoid.numpy()))
print('AN with Tanh : {}\n{}'.format(y_tanh.shape, y_tanh.numpy()))
print('AN with Relu : {}\n{}'.format(y_relu.shape, y_relu.numpy()))

# forward propagation (manual)
print('\n=========\n')

W, B = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x, W) + B
a = 1 / (1 + exp(-z))
print("Activation value(Tensorflow) : {}\n{}".format(y_sigmoid.shape, y_sigmoid.numpy()))
print("Activation value(manual) : {}\n{}".format(a.shape, a.numpy()))

AN with Sigmoid : (1, 1)
[[0.14416163]]
AN with Tanh : (1, 1)
[[-0.27314395]]
AN with Relu : (1, 1)
[[2.4666135]]


Activation value(Tensorflow) : (1, 1)
[[0.14416163]]
Activation value(manual) : (1, 1)
[[0.14416163]]


## Artificial Neurons

In [16]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.math import exp, maximum

activation = 'sigmoid'
# activation = 'tanh'
# activation = 'relu'

x = tf.random.uniform(shape=(1,10)) # input setting

dense = Dense(units=1, activation=activation) # imp. an affine + activation

y_tf = dense(x)
W, B = dense.get_weights()

# calculate activation value manually
y_man = tf.linalg.matmul(x, W) + B
if activation == 'sigmoid':
  y_man = 1/(1+exp(-y_man))
elif activation == 'tanh':
  y_man = (exp(y_man) - exp(-y_man))/(exp(y_man) + exp(-y_man))
elif activation == 'relu':
  y_man = maximum(y_man,0)

print("Activation : ", activation)
print("y_tf : {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("y_man : {}\n{}\n".format(y_man.shape, y_man.numpy()))

Activation :  sigmoid
y_tf : (1, 1)
[[0.31698993]]

y_man : (1, 1)
[[0.3169899]]



## Minibatches

In [20]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 8, 10 # set input params
x = tf.random.normal(shape=(N, n_feature)) # generate minibatch

dense = Dense(units=1, activation='relu') # imp. an AN
y_tf = dense(x) # forward propagation

W, B = dense.get_weights() # get weight/bias

# print results
print("shape of x  : {}".format(x.shape))
print("shape of W  : {}".format(W.shape))
print("shape of B  : {}".format(B.shape))

shape of x  : (8, 10)
shape of W  : (10, 1)
shape of B  : (1,)


In [21]:
## output calculations

In [25]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.math import exp 

N, n_feature = 8, 10 # set input params
x = tf.random.normal(shape=(N, n_feature)) # generate minibatch

dense = Dense(units=1, activation='sigmoid') # imp. an AN
y_tf = dense(x) # forward propagation (Tensorflow)

W, B = dense.get_weights() # get weight/bias

y_man = tf.linalg.matmul(x, W) + B # forward propagation (Manual)
y_man = 1/(1+exp(-y_man))

# print results
print("output(Tensorflow) : \n", y_tf.numpy(), '\n')
print("outout(manual) : \n", y_man.numpy(), '\n')


output(Tensorflow) : 
 [[0.31565124]
 [0.41935363]
 [0.23147021]
 [0.4756208 ]
 [0.60098875]
 [0.19077937]
 [0.3165718 ]
 [0.85131687]] 

outout(manual) : 
 [[0.31565124]
 [0.41935366]
 [0.23147021]
 [0.4756208 ]
 [0.60098875]
 [0.19077936]
 [0.3165718 ]
 [0.8513169 ]] 



/root
