# Max/Avg Pooling

## Max Pooling

In [13]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling1D

L, f, s = 10, 2, 1

x = tf.random.normal(shape=(1, L, 1)) # 3차원일 때 계산 가능. 
pool_max = MaxPooling1D(pool_size=f, strides=s)
pooled_max = pool_max(x)

print("x: {}\n{}".format(x.shape, x.numpy().flatten()))
print("pooled_max(Tensorflow) : {}\n{}".format(pooled_max.shape, pooled_max.numpy().flatten()))

x = x.numpy().flatten()
pooled_max_man = np.zeros((L-f+1,)) 
for i in range(L-f+1):
  window = x[i:i+f]
  pooled_max_man[i] = np.max(window)
  # print(pooled_max_man)

print("pooled_max(Manual) : {}\n".format(pooled_max_man))


pooled_max(Manual) : [ 0.43230307  0.43230307  0.02597376 -0.14710608 -1.00229859 -0.11765051
  1.00736463  1.00736463 -0.03045913]



## Average Pooling

In [15]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import AveragePooling1D

L, f, s = 10, 2, 1

x = tf.random.normal(shape=(1, L, 1)) # 3차원일 때 계산 가능. 
pool_avg = AveragePooling1D(pool_size=f, strides=s)
pooled_avg = pool_avg(x)


print("x: {}\n{}".format(x.shape, x.numpy().flatten()))
print("pooled_avg(Tensorflow) : {}\n{}".format(pooled_avg.shape, pooled_avg.numpy().flatten()))

x = x.numpy().flatten()
pooled_avg_man = np.zeros((L-f+1,)) 
for i in range(L-f+1):
  window = x[i:i+f]
  pooled_avg_man[i] = np.mean(window)
  # print(pooled_max_man)

print("pooled_avg(Manual) :\n{}".format(pooled_avg_man))




x: (1, 10, 1)
[ 0.5806279  -0.11873829  1.6386622   0.580814    1.782138   -0.87815917
  0.34080777 -0.4899891  -0.47728065 -0.46357438]
pooled_avg(Tensorflow) : (1, 9, 1)
[ 0.23094481  0.75996196  1.1097381   1.181476    0.4519894  -0.26867568
 -0.07459067 -0.4836349  -0.4704275 ]
pooled_avg(Manual) :
[ 0.23094481  0.75996196  1.10973811  1.181476    0.45198941 -0.26867568
 -0.07459067 -0.48363489 -0.47042751]


# Max/Avg Pooling

## 2D Max Pooling

In [19]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D

N, n_H, n_W, n_C = 1, 5, 5, 1
f, s = 2, 1

x = tf.random.normal(shape=(N, n_H, n_W, n_C))
pool_max = MaxPooling2D(pool_size=f, strides=s)
pooled_max = pool_max(x)

print("x: {}\n{}".format(x.shape, x.numpy().squeeze()))
print("pooled_max(Tensorflow) : {}\n{}".format(pooled_max.shape, pooled_max.numpy().squeeze()))

x = x.numpy().squeeze()
pooled_max_man = np.zeros(shape=(n_H - f + 1, n_W - f + 1))
for i in range(n_H -f + 1):
  for j in range(n_W -f + 1):
    window = x[i:i+f, j:j+f]
    pooled_max_man[i, j] = np.max(window)

print("pooled_max(Manual) : {}\n{}".format(pooled_max_man.shape, pooled_max_man))  

x: (1, 5, 5, 1)
[[-0.11996275  0.18582931  0.44811437 -2.3166907   0.10782502]
 [ 1.7188647   0.50383055 -0.24422099 -0.5284736  -0.71517366]
 [-0.20210882 -0.8496307  -0.43785483  1.835503   -0.72683686]
 [ 0.33328086  0.24795516  1.2561157   0.15867923  2.0626938 ]
 [ 2.6990075  -1.0460392  -1.1551968  -0.47410753  1.9190351 ]]
pooled_max(Tensorflow) : (1, 4, 4, 1)
[[1.7188647  0.50383055 0.44811437 0.10782502]
 [1.7188647  0.50383055 1.835503   1.835503  ]
 [0.33328086 1.2561157  1.835503   2.0626938 ]
 [2.6990075  1.2561157  1.2561157  2.0626938 ]]
pooled_max(Manual) : (4, 4)
[[1.71886468 0.50383055 0.44811437 0.10782502]
 [1.71886468 0.50383055 1.83550298 1.83550298]
 [0.33328086 1.25611567 1.83550298 2.06269383]
 [2.69900751 1.25611567 1.25611567 2.06269383]]


## 2D Average Pooling

In [21]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import AveragePooling2D

N, n_H, n_W, n_C = 1, 5, 5, 1
f, s = 2, 1

x = tf.random.normal(shape=(N, n_H, n_W, n_C))
pool_avg = AveragePooling2D(pool_size=f, strides=s)
pooled_avg = pool_avg(x)

print("x: {}\n{}".format(x.shape, x.numpy().squeeze()))
print("pooled_avg(Tensorflow) : {}\n{}".format(pooled_avg.shape, pooled_avg.numpy().squeeze()))

x = x.numpy().squeeze()
pooled_avg_man = np.zeros(shape=(n_H - f + 1, n_W - f + 1))
for i in range(n_H -f + 1):
  for j in range(n_W -f + 1):
    window = x[i:i+f, j:j+f]
    pooled_avg_man[i, j] = np.mean(window)

print("pooled_avg(Manual) : {}\n{}".format(pooled_avg_man.shape, pooled_avg_man))  

x: (1, 5, 5, 1)
[[ 1.2556248  -0.7113386  -0.6657185  -0.1771483   0.64586395]
 [-0.6604482   1.5283269   0.3955521   1.0075039   2.0399806 ]
 [-0.23434629 -0.95503914 -0.57146376 -0.19074748 -0.82568806]
 [ 0.07381323  0.32564598 -0.83676416 -0.72356427 -0.23446925]
 [-0.6864427  -0.72069263 -0.27341676  0.05199142  1.3934609 ]]
pooled_avg(Tensorflow) : (1, 4, 4, 1)
[[ 0.35304123  0.13670547  0.1400473   0.87905   ]
 [-0.08037668  0.099344    0.16021116  0.5077622 ]
 [-0.19748156 -0.50940526 -0.58063495 -0.49361727]
 [-0.25191903 -0.3763069  -0.44543844  0.12185469]]
pooled_avg(Manual) : (4, 4)
[[ 0.35304123  0.13670547  0.1400473   0.87905002]
 [-0.08037668  0.099344    0.16021116  0.50776219]
 [-0.19748156 -0.50940526 -0.58063495 -0.49361727]
 [-0.25191903 -0.37630689 -0.44543844  0.12185469]]
