# Conv Layers with Filters 

## Shapes with Filters

In [2]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 28, 28, 3 # N은 바뀌지 않음 
n_filter = 5
k_size = 3 # kernel size ==> f

images = tf.random.uniform(minval=0, maxval=1, shape=(N, n_H, n_W, n_C))

conv = Conv2D(filters=n_filter, kernel_size=k_size)

Y = conv(images)

W, B = conv.get_weights()

print('input image : {}'.format(images.shape))
print("W/B : {} / {}".format(W.shape, B.shape))
print("output image : {}".format(Y.shape)) 

input image : (1, 28, 28, 3)
W/B : (3, 3, 3, 5) / (5,)
output image : (1, 26, 26, 5)


## Computations with Filters

In [23]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3 
n_filter = 3
k_size = 4 # kernel size ==> f
images = tf.random.uniform(minval=0, maxval=1, shape=(N, n_H, n_W, n_C))

# Forward Propagation
conv = Conv2D(filters=n_filter, kernel_size=k_size)
Y = conv(images)
Y = np.transpose(Y.numpy().squeeze(), (2,0,1))

# print("Y(Tensorflow) : ", Y.numpy())

W, B = conv.get_weights()
images = images.numpy().squeeze()

Y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1, n_filter))
for c in range(n_filter):
  c_W = W[:, :, :, c]
  c_b = B[c]

  for h in range(n_H - k_size  + 1):
    for w in range(n_W - k_size + 1):
      window = images[h:h+k_size, w:w+k_size, :]
      conv = np.sum(window*c_W) + c_b

      Y_man[h, w, c] = conv

    print("Y(Manual) : ", np.transpose(Y_man, (2,0,1)))

Y(Manual) :  [[[-0.29113895  0.01894665]
  [ 0.          0.        ]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]]
Y(Manual) :  [[[-0.29113895  0.01894665]
  [-0.79150128 -0.32464659]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]]
Y(Manual) :  [[[-0.29113895  0.01894665]
  [-0.79150128 -0.32464659]]

 [[-0.97480845 -0.4059453 ]
  [ 0.          0.        ]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]]
Y(Manual) :  [[[-0.29113895  0.01894665]
  [-0.79150128 -0.32464659]]

 [[-0.97480845 -0.4059453 ]
  [-0.39323807 -0.69562972]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]]
Y(Manual) :  [[[-0.29113895  0.01894665]
  [-0.79150128 -0.32464659]]

 [[-0.97480845 -0.4059453 ]
  [-0.39323807 -0.69562972]]

 [[-0.42879999 -0.25904429]
  [ 0.          0.        ]]]
Y(Manual) :  [[[-0.29113895  0.01894665]
  [-0.79150128 -0.324646

In [15]:
import numpy as np

images = np.random.randint(low=0, high=10, size=(2,3,4))
for c in range(4):
  # print(images[:, :, c])
  break

images = np.transpose(images, (2,0,1))
for c in range(4):
  print(images[c, :, :])

[[7 4 9]
 [1 3 2]]
[[1 4 6]
 [5 5 9]]
[[9 7 1]
 [6 3 1]]
[[7 3 8]
 [6 4 0]]


# Conv Layers with Activation Functions

## Conv Layers with Activation Functions 

In [26]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3 
n_filter = 3 # neuron의 개수 
k_size = 4 # kernel size ==> f
images = tf.random.uniform(minval=0, maxval=1, shape=(N, n_H, n_W, n_C))

# Forward Propagation
conv = Conv2D(filters=n_filter, kernel_size=k_size, activation='sigmoid')
Y = conv(images)
Y = np.transpose(Y.numpy().squeeze(), (2,0,1)) 

# print("Y(Tensorflow) : ", Y.numpy())

W, B = conv.get_weights()
images = images.numpy().squeeze()

Y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1, n_filter))
for c in range(n_filter):
  c_W = W[:, :, :, c]
  c_b = B[c]

  for h in range(n_H - k_size  + 1):
    for w in range(n_W - k_size + 1):
      window = images[h:h+k_size, w:w+k_size, :]
      conv = np.sum(window*c_W) + c_b
      conv = 1/(1+np.exp(-conv))

      Y_man[h, w, c] = conv

print("Y(Manual) : ", np.transpose(Y_man, (2,0,1)))

Y(Manual) :  [[[0.62180265 0.76775445]
  [0.79980172 0.74457332]]

 [[0.16224888 0.39913339]
  [0.18996118 0.25916207]]

 [[0.55455776 0.71781146]
  [0.72485382 0.6572594 ]]]
