# Conv Layers

## Shapes of Conv Layers

In [16]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 28, 28, 5
n_filter=10 # l1 
k_size=3 # f (kernel size, window size) 

images = tf.random.uniform(minval=0, maxval=1, shape=(N,n_H,n_W,n_C))
conv = Conv2D(filters = n_filter, kernel_size=k_size)
y=conv(images)
W, B = conv.get_weights()


print(images.shape)
print(W.shape)
print(B.shape)
print(y.shape)

(1, 28, 28, 5)
(3, 3, 5, 10)
(10,)
(1, 26, 26, 10)


## Correlation Calculation

In [26]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 1
n_filter=1
k_size=3 # f

images = tf.random.uniform(minval=0, maxval=1, shape=(N,n_H,n_W,n_C))
conv = Conv2D(filters = n_filter, kernel_size=k_size)
y=conv(images)
print("Y(Tensorflow) : ", y.numpy().squeeze().shape)
W, B = conv.get_weights()

####
images = images.numpy().squeeze()
W = W.squeeze()

y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1)) # 먼저 선언해주기 
for i in range(n_H - k_size + 1):
  for j in range(n_W - k_size + 1):
    window = images[i : i+k_size , j : j + k_size]
    y_man[i,j] = np.sum(window*W) + B

print("Y(Manual) :\n", y_man)

Y(Tensorflow) :  (3, 3)
Y(Manual) :
 [[-0.17782167  0.05653065 -0.49518126]
 [-0.46050531 -0.63567066  0.09783878]
 [-0.25700805  0.33131561  0.0665929 ]]


## Correlation with n-channel 

In [27]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3 # channel이 바뀐다고 해서 weight, bias가 바뀌지 않음. 
n_filter=1
k_size=3 # f

images = tf.random.uniform(minval=0, maxval=1, shape=(N,n_H,n_W,n_C))
conv = Conv2D(filters = n_filter, kernel_size=k_size)
y=conv(images)
print("Y(Tensorflow) : ", y.numpy().squeeze().shape)
W, B = conv.get_weights()

####
images = images.numpy().squeeze()
W = W.squeeze()

y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))
for i in range(n_H - k_size + 1):
  for j in range(n_W - k_size + 1):
    window = images[i : i+k_size , j : j + k_size, :] # 여기만 바뀜 
    y_man[i,j] = np.sum(window*W) + B

print("Y(Manual) :\n", y_man)

Y(Tensorflow) :  (3, 3)
Y(Manual) :
 [[0.2737211  0.45337757 0.58229768]
 [0.38881022 0.54598999 0.40068793]
 [0.74647772 0.68667763 0.50215912]]
